### ISSUE TITLE
native go modules support proposal (originally named v2 proposal)

### ISSUE THREAD

**Issue by Bobgy** [google/go-licenses#70]
## Updates

2022-03-12: https://github.com/google/go-licenses/issues/70#issuecomment-1065797789 This will be released as v1.1 instead, because the breaking change might not affect anyone now (TL;DR there's only a regression for people still using GOPATH). Also renamed this issue to make the purpose clearer.

2021-1-11: https://github.com/google/go-licenses/issues/70#issuecomment-1003285780 I sent out a bunch of PRs for merging changes back to go-licenses repo. The final PRs I'm sending now try to change as minimal as possible. There are no substantial command/arg changes and there are no significant behavior changes. The only major theme is using go modules information to get license URLs more stably than the v1 go-licenses tool.

## Original Proposal

Hi everyone, I'm building a rewrite of go-licenses that I propose to be go-licenses/v2.
~~Latest version on my dev branch: https://github.com/Bobgy/go-licenses/blob/main/v2.~~ No longer latest.
Built binary releases: https://github.com/Bobgy/go-licenses/releases.

I initially built it as a new tool, but after chatting with @wlynch, we agreed that it would better be v2 of this tool rather than a new brand.

The major changes are:
* only supports go modules, it can get license URL for modules without a need for you to vendor your dependencies.
* ~~do not assume each package has a single license, v2 will scan all the files for each module to find licenses.~~ Deferred for future considerations.

For more details, refer to [the README](https://github.com/Bobgy/go-licenses/blob/initial/v2/README.md).

The new tool already addresses many open issues:

* https://github.com/google/go-licenses/issues/32 vanity urls are curled and extracted to find the repo
* https://github.com/google/go-licenses/issues/33 urls are now versioned according to go modules info
* https://github.com/google/go-licenses/issues/38 now we use modules info, no custom parsing
* https://github.com/google/go-licenses/issues/53 proper go modules support
* https://github.com/google/go-licenses/issues/64 is a subproblem of proper go modules support

Deprioritized features
* https://github.com/google/go-licenses/issues/39 we scan all files for licenses, so we can find UNLICENSE files too

and might help the following (but needs confirmation):
* https://github.com/google/go-licenses/issues/18

## Roadmap
* [x] https://github.com/google/go-licenses/pull/101
* [ ] CSV command
  * [x] Get modules/packages list
    * [x] P0 https://github.com/google/go-licenses/pull/82
  * [x] https://github.com/google/go-licenses/pull/94
  * [ ] #110 
  * [ ] Config file customization & overrides
* [x] Documentation
  * [x] https://github.com/google/go-licenses/pull/111
* [ ] Smaller Issues
  * [ ] P1 Replace glog [comment](https://github.com/google/go-licenses/pull/94/files/5683d9873cb99b8d04097910d92806378174cf2c..b26545052058c774ace5c4c85d70ae0781c3fff2#r790208548)

**Comment by Bobgy** [comment]
## Roadmap

Based on https://github.com/google/go-licenses/pull/67#pullrequestreview-686805811.

> Unfortunately this is a very large change. I've left some initial comments as a first pass, but we'll likely need to do multiple iterations to resolve everything. Something that would greatly help me out for reviewing is if we could break this up into separate PRs. Here's some individual chunks I see that might be good places to break this apart:

I'll be sending several PRs to gradually implement the new tool instead.

Here, I'm using this issue to track progress.

**Comment by Bobgy** [comment]
## Tasks
* [ ] CSV command
  * [ ] Get licenses from binary
  * [ ] Use module cache for license source
  * [ ] Subfile license checking
  * [ ] Config file customization & overrides
* [ ] Save command
   * [ ] Single licenses.txt output
   * [ ] Copy source folders for licenses that require so
* [ ] Check command

**Comment by mythi** [comment]
Suggest: Source command: compress sources

**Comment by Bobgy** [comment]
I sent out a bunch of PRs, and a few more are waiting.
The rough idea is starting from a copy of v1 go-licenses tool and gradually replace each command with the new implementation.

**Comment by Bobgy** [comment]
@wlynch let's track general discussion in the main issue?

> General question before I start reviewing these PRs in more details - are the changes to csv/check changes introducing any changes w.r.t input/outputs of the commands, or is this strictly an upgrade using module info?

No, there are no substantial changes to io.

There is a minor and optional output format change of adding a space after each comma to make it convenient to click the license URL in terminal/editor, do you have any concerns?

Also, git-url argument is removed, because it's no longer used. (But I am reconsidering this, because it may be useful for the main module.)

> If there isn't anything that would break compatibility with existing clients, it might make sense to just merge these into v1. 👀 
> The bits I was primarily concerned with the original v2 proposal were the new commands and the different output format.

Well, the major breaking change is that we no longer support non go module projects. That's probably worth a v2. What do you think?

**Comment by Bobgy** [comment]
@wlynch https://github.com/google/go-licenses/pull/95, https://github.com/google/go-licenses/pull/101 and https://github.com/google/go-licenses/pull/94 are ready for review : )

**Comment by Bobgy** [comment]
Note, I created a github release in my fork in case anyone want to try the proposed new tool: https://github.com/Bobgy/go-licenses/releases/tag/v0.1.0-2022-01-20

**Comment by Bobgy** [comment]
Created a new release that can be installed from source: https://github.com/Bobgy/go-licenses/releases/tag/v2.0.0-alpha.0.

```bash
go get github.com/Bobgy/go-licenses/v2
go-licenses --help
```

to try my fork, it's mostly ready to use.

**Comment by oxisto** [comment]
Is it somehow planned / possible to configure the `check` command, e.g. not only check for forbidden license but also for restricted? Or to configure the list of forbidden libraries? Or to at least print out the license type in the csv so I can grep for it? :)

**Comment by Bobgy** [comment]
Hi @oxisto, it's not in the scope. You might want to file a separate issue for this feature request.

**Comment by oxisto** [comment]
> Hi @oxisto, it's not in the scope. You might want to file a separate issue for this feature request.

got it. thanks for your answer!

**Comment by Bobgy** [comment]
Update, based on discussion with @wlynch, we think that the breaking change for GOPATH might not be noticeable, because we don't know anyone still using GOPATH now. Therefore, we will consider releasing the next version as v1.1 instead. There won't be an actual v2.

Let us know if you use go-licenses and still use GOPATH, we can consider making changes in this proposal an actual v2 when needed.

**Comment by Bobgy** [comment]
The major changes have been released as v1.1.
Future improvements will be tracked individually in issues.
